#!/usr/bin/env bash

MY_BLACK="#000000"
MY_DARK_GREY="#262626"
MY_LIGHT_GREY="#626262"
MY_WHITE="#FFFFFF"
MY_HOT_PINK="#FF0087"
MY_LIGHT_PINK="#FF5F87"
MY_GREEN="#00FF5F"
MY_LIGHT_GREEN="#5FFF87"
MY_YELLOW="#FFFF5F"
MY_LIGHT_YELLOW="#D7FF87"
MY_BLUE="#005FFF"
MY_LIGHT_BLUE="#00AFFF"
MY_DARK_PURPLE="#AF00FF"
MY_PURPLE="#AF5FD7"
MY_DARK_CYAN="#66FFFF"
MY_CYAN=$MY_DARK_CYAN

: "${ff:="/tmp/4wm.fifo"}"

tags=("^i(/home/dct/.bitmaps/w1.xbm)" \
        "^i(/home/dct/.bitmaps/w2.xbm)" \
        "^i(/home/dct/.bitmaps/w3.xbm)" \
        "^i(/home/dct/.bitmaps/w4.xbm)" \
        "^i(/home/dct/.bitmaps/w5.xbm)" \
        "^i(/home/dct/.bitmaps/w6.xbm)" \
        "^i(/home/dct/.bitmaps/w7.xbm)" \
        "^i(/home/dct/.bitmaps/w8.xbm)" \
        "^i(/home/dct/.bitmaps/w9.xbm)" )

layouts=("^i(/home/dct/.bitmaps/left_arrow.xbm)" \
        "^i(/home/dct/.bitmaps/right_arrow.xbm)" \
        "^i(/home/dct/.bitmaps/down_arrow.xbm)" \
        "^i(/home/dct/.bitmaps/up_arrow.xbm)" \
        "^i(/home/dct/.bitmaps/full.xbm)") 

# Check if it's a pipe, otherwise create it
[[ -p $ff ]] || mkfifo -m 600 "$ff"

while read -t 60 -r wmout || true; do
    desktops=( $(cut -d"|" -f1 <<< "$wmout") )
    title="$(cut -d"|" -f2- <<< "$wmout")"

    if [[ "${desktops[@]}" =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        unset tmp

        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"

            # Tags labels
            label="${tags[$d]}"      

            # Is this the current desktop ? save the layout
            ((c)) && fg=$MY_BLUE && layout="${layouts[$m]}" \
                  || fg=$MY_LIGHT_GREY
                
            # Has windows ?
            ((w)) && !((c))&& fg=$MY_WHITE

            # Urgent windows ?
            ((u)) && fg=$MY_YELLOW

            tmp+="^fg($fg)$label ^bg()^fg()"
        done
    fi

    # Merge the clients indications, the tile and the info
    echo -e " $tmp^fg($MY_GREEN)$layout ^fg($MY_WHITE)<$title>"
done < "$ff" | dzen2 -x '0' -y '784' -h '16' -w '640' -ta l -fg '#FFFFFF' -bg '#000000' -fn 'Gohu:size=8' &

(conky -c ~/.config/conky/conky_4wm | dzen2 -x '640' -y '784' -h '16' -w '640' -ta r -fg '#FFFFFF' -bg '#000000' -fn 'Gohu:size=8') &

~/Temp/4wm/4wm > "$ff"
