.TH frankensteinwm 1 frankensteinwm
.SH NAME
frankensteinwm \- a dynamic tiling window manager
.SH SYNOPSIS
.B frankensteinwm
.RB [ \-v ]
.SH DESCRIPTION
frankensteinwm is a small, lightweight, versatile, dynamic tiling window manager with two borders.
.P
.SH MODES
There is one tiling layout with four modes that split the current window in half and add the new window to either the left, right,
top, or bottom.
.P
.B frankensteinwm
other modes are:
.I Monocle mode
, a fullscreen mode, where the clients take up the entire workspace excluding the gap, and 
additional clients are hidden behind the current shown window.
.I Video mode
, a fullscreen mode, where the clients take up the entire workspace, and additional clients
are hidden behind the current shown window.
.I Floating mode
where, windows can move and be resized freely in the screen space. Windows
retain their floating status until the user switches to a tiling mode.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE
.SS Status bar
frankensteinwm does not provide a status bar. Consistent with the Unix philosophy,
frankensteinwm provides information to the status bar or panel of choice via text.
.SS Keyboard and mouse commands
All of
.I frankensteinwm's
commands can be customized by editing
.I config.h
and recompiling. The default key-bindings include:
.TP
.B Mod1\-Shift\-Return
Start
.BR xterm (1).
.TP
.B Mod1\-b
Toggles the panel on and off.
.TP
.B Mod1\-Shift\-w
Sets tiling layout to the top.
.TP
.B Mod1\-Shift\-a
Sets tiling layout to the left.
.TP
.B Mod1\-Shift\-s
Sets tiling layout to the bottom.
.TP
.B Mod1\-Shift\-d
Sets tiling layout to the right.
.TP
.B Mod1\-Shift\-m
Sets monocle layout.
.TP
.B Mod1\-Shift\-b
Sets video layout.
.TP
.B Mod1\-Control\-k
Moves focus up.
.TP
.B Mod1\-Control\-h
Moves focus left.
.TP
.B Mod1\-Control\-j
Moves focus down.
.TP
.B Mod1\-Control\-l
Moves focus right.
.TP
.B Mod1\-Backspace
Focus the window that raised an urgent hint. If no such window in current desktop,
search other desktops, and focus the desktop and window that raised the urgent hint.
.TP
.B Mod1\-Shift\-c
Close focused window.
.TP
.B Mod1\-Shift\-q
Quit frankensteinwm.
.TP
.B Mod1\-F{1..n}
Move to the nth workspace. By default,
.I frankensteinwm
is configured with nine workspaces.
.TP
.B Mod1\-Shift\-F{1..n}
Move focused window to nth workspace.
.TP
.B Mod1\-Control\-minus
Rotates backwards through desktops.
.TP
.B Mod1\-Control\-equal
Rotates forwards through desktops.
.TP
.B Mod1\-Shift\-minus
Rotates backwards through desktops with windows.
.TP
.B Mod1\-Shift\-equal
Rotates forwards through desktops with windows.
.TP
.B Mod1\-h
Increases tiled window size to the left.
.TP
.B Mod1\-l
Increases tiled window size to the right.
.TP
.B Mod1\-j
Increases tiled window size to the bottom.
.TP
.B Mod1\-k
Increases tiled window size to the top.
.TP
.B Mod1\-t
pushes a floating window into tiling.
.TP
.B Mod1\-minus
decreases desktop's gap between windows.
.TP
.B Mod1\-equal
increases desktop's gap between windows.
.TP
.B Mod1\-Button1
Dragging the mouse will move the selected window.
.TP
.B Mod1\-Button3
Dragging the mouse will resize the selected window.
.TP
.SH CUSTOMIZATION
.I frankensteinwm
is customized by copying
.I config.def.h
to
.I config.h
and (re)compiling the source code.
.SH SEE ALSO
.BR xterm (1)
.SH BUGS
.I frankensteinwm
is under active development. Please report all bugs to the author.
.SH AUTHOR
Derek Taaffe <cameron.taaffe at gmail.com>
